[package]
name = "jinglepings-better"
version = "0.1.0"
authors = ["Yoeri Otten <yoeori@live.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rawsock = "0.1"
image = "0.22.3"
pnet = "0.35.0"